/* The published grades, name and price only, generated by tools/build-pages.py
   from reference/grades.json. The configurator renders the full trim data into
   its own page at build time; this is the small share of it that Compare needs
   on every page it runs on. Do not edit by hand. */
(function (window) {
    'use strict';
    window.Grades = {
        "x-trail": [
                {
                        "name": "S 2WD 7 Seats",
                        "price": 107999
                },
                {
                        "name": "S 4WD 5 Seats",
                        "price": 109999
                },
                {
                        "name": "S 4WD 7 Seats",
                        "price": 116499
                },
                {
                        "name": "SV 4WD 7 Seats",
                        "price": 130999
                },
                {
                        "name": "SV+ 4WD 7 Seats",
                        "price": 144999
                },
                {
                        "name": "SL 4WD 7 Seats"
                },
                {
                        "name": "N-TREK",
                        "price": 150999
                }
        ],
        "pathfinder": [
                {
                        "name": "3.5L V6 S 2WD",
                        "price": 164999
                },
                {
                        "name": "3.5L V6 S 4WD",
                        "price": 179999
                },
                {
                        "name": "3.5L V6 SV 2WD",
                        "price": 192999
                },
                {
                        "name": "3.5L V6 SV 4WD",
                        "price": 206999
                },
                {
                        "name": "3.5L V6 SL 4WD",
                        "price": 227999
                }
        ],
        "altima": [
                {
                        "name": "S",
                        "price": 112700
                },
                {
                        "name": "SV",
                        "price": 127500
                },
                {
                        "name": "SL",
                        "price": 141500
                }
        ],
        "x-terra": [
                {
                        "name": "SE",
                        "price": 118999
                },
                {
                        "name": "TITANIUM",
                        "price": 129999
                },
                {
                        "name": "PLATINUM",
                        "price": 163999
                }
        ],
        "z": [
                {
                        "name": "Performance",
                        "price": 261999
                }
        ]
};
})(window);
